### ISSUE TITLE
Uttesting Confluence intern dokumentasjon produktteam

### ISSUE THREAD

**Issue by SnorreTE** [Altinn/styringssystem#14]
![Image](https://github.com/user-attachments/assets/cff2afa6-d3c5-4bb0-9e5f-25507a613dda)

Ref telefonsamtale med Hanne i går skyves avgjørelsen rundt Confluence nedover i organisasjonen. Det blir pekt på team Styringssystem, men team produktutvikling som ansvarlig for Devops prosess og dokumentasjon har jo også dette innfor sitt ansvarsområde.
Foreløpig konklusjon er at utviklingsteamene som er i gang med arbeid rundt «rammeverk - intern dokumentasjon - Produktteam (inkl plattform)» tester ut Confluence i dette arbeidet.

Vi trenger en kort begrunnelse fra dere for valg av Confluence til Devops dokumentasjon  (en slide/a4 punktliste)

Det er jo FEL/Digdir sin Confluence som skal benyttes. De har vel sikkert en del på punktene nedenfor:

•	Sikkerhetsvurdering
•	Personvern vurdering
•	Risikovurdering
•	Retningslinjer 
•	Merkantilt/lisenser

"Plan" videre arbeid:
 
Videre arbeid uttesting Confluence

- Utvalgte team får tilgang til FELs Confluence nå i juli (Randi/Ronny)
- Ronny etablerer struktur for BOD i Confluence og onboarder team

 

1. Hanne/Ronny leverer dokumentasjon på behov fra produkt teamene (Hvorfor Confluence)
2. FEL leverer risikovurdering med mer for Confluence (levert av Randi)
3. Verktøyansvar i BOD. Div kjøreregler for bruk mm
4. Team styringssystem orienterer lederlag om uttesting og budsjett behov (august)
  - Ca 10 000 per måned i testperiode
  - Ca 120 000 i fast årlig utgift ved videre drift
IT drift:
-Ronny: Se oversikt over kostnader for Confluence – er dette greit kan vi bestille? Dette er for 100 brukere og primært utviklingsteamene. Tilleggene for dokumentasjon av diagrammer kan diskuteres. Så minimum er 27000 nå i første omgang.

                Har fått pris: 
                
                Atlassian Cloud. Confluence (Cloud) ANNUAL Standard, up to 300 users updated from 200 users
                27 081,56
                
                Atlassian Cloud. draw.io Diagrams & Whiteboards Cloud app ANNUAL Standard, up to 300 users updated from 200 users
                4 739,36
                
                Atlassian Cloud. Gliffy Diagrams for Confluence Cloud app ANNUAL Standard, up to 300 uses updated from 200 users
                12 525,29
                
                Atlassian Cloud. Mermaid Integration for Confluence Cloud app ANNUAL Standard, up to 300 users updated from 200 users
                744,75
                
                Totalt
                45 090,96
                
                Skal jeg bestille? 
                Vi må oppgradere alle 4 da det er tillegg som er i bruk og alle må følge samme lisensantall. 

5. Avsjekk Økonomi team budsjett midler
6. Vedlegg risikoanalyse fra pkt 2 og dokumentasjon behov fra pkt 1

```[tasklist]
### Tasks
- [x] Møte FEL
- [ ] Dokumentasjon produktteam valg av Confluence
- [x] Vurderinger Confluence i FEL
- [x] Orienteringssak ledermøte
- [x] Prisavklaring
- [x] Godkjennelse fra ledermøte/avd dir
- [x] Oppstart rutiner og "drift" Confluence
- [ ] Møte med tilretteleggingsteamene
- [ ] Utarbeide rutinebeskrivelse
```

```[tasklist]
### Tasks
```

**Comment by SnorreTE** [comment]
Bedt Hanne L om beskrivelse av hvorfor produktteamene må bruke Confluence. Må på plass før videre arbeid med saksfremlegg.

**Comment by WencheFylken** [comment]
Invitasjon til møte med tilretteleggingsteamene slik at de kan ta Confluence i bruk

**Comment by SnorreTE** [comment]
Issue for å få Confluence godkjent i lederlag og etablert organisering lukkes, 
Eget issue for rutiner og "drift" med mer rundt Confluence bruk opprettes @WencheFylken
